# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml

variables:
  # Only used by the container image
  IMAGE_BUILD_FROM: docker.io/arm32v7/debian:10

.matrix:
  parallel:
    matrix:
      - SUBDIR:
          - container
          - debian9
          - debian10

container:
  # We replace everything except the "rules" section here...
  extends:
    - .container:publish
    - .matrix
  # If we had a qemu-static instead on the CI machines,
  # we could do this using the "container" x86-64 image and just build this as a
  # normal container.
  #
  # issue: ModioAB/agile#2083
  tags:
    - arm
  image:
    name: registry.gitlab.com/modioab/arm-image/container:master
    # debian + gitlab workaround for /bin/sh => /bin/dash
    entrypoint: [""]
  script:
    - make -C ${SUBDIR} login
    - make -C ${SUBDIR} build-publish
...
