# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml


.matrix:
  parallel:
    matrix:
      - SUBDIR:
          - debian9
          - debian10


build:
  # We replace everything except the "rules" section here...
  extends:
    - .container:build
    - .matrix
  # If we had a qemu-static instead on the CI machines,
  # we could do this using the "container" x86-64 image and just build this as a
  # normal container.
  #
  # Now, this essentially reproduces a "container" image in the before_script,
  # and does some debian-specific hacking in the "script" section.
  tags:
    - arm
  image:
    name: arm32v7/debian
    # debian + gitlab workaround for /bin/sh => /bin/dash
    entrypoint: [""]

  # re-create the container image, but in armv7
  before_script:
    - apt-get update
    - apt-get -y install bash docker.io make curl git ncurses-bin


publish:
  extends:
    - .container:publish
    - .matrix
...
