# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml


.manual:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
    - when: never


.rootfs:
  stage: build
  tags:
    - arm
  before_script:
    - sed -i s:httpredir:ftp.nl:g /etc/apt/sources.list
    - apt-get update
    - apt-get install -y -qq make debootstrap bash
  script:
    - make -C debian9 rootfs.tar
  artifacts:
    paths:
      - debian9/rootfs.tar
    expire_in: 1 day


upstream:armv7:build:
  extends:
    - .rootfs
    - .manual
  image:
    name: arm32v7/debian
    entrypoint: [""]


debian:armv7:build:
  extends:
    - .rootfs
  image:
    # Old oneshot image
    # name: registry.gitlab.com/modioab/arm-image:debian9-oneshot
    #
    # Upstream image
    # name: arm32v7/debian
    #
    # Latest image
    name: registry.gitlab.com/modioab/arm-image/debian9:master
    entrypoint: []


upstream:armv7:publish:
  extends:
    - .container:publish
    - .manual
  variables:
    IMAGE_TAG_SUFFIX: "oneshot"

  needs:
    - upstream:armv7:build
  script:
    - make -C debian9 login
    - make -C debian9 build-publish


debian:armv7:publish:
  extends:
    - .container:publish
  needs:
    - debian:armv7:build
  script:
    - make -C debian9 login
    - make -C debian9 build-publish
...
