# vim: expandtab:ts=2:sw=2:fdm=marker
---
stages:
  - build
  - publish

variables:
  # Podman defaults to OCI images, since 2019-02-15+ onwards, gitlab registry
  # fails to work properly with the default `oci` images.
  # TODO: Test & bug-report this
  BUILDAH_FORMAT: docker

before_script:
  - make -f build.mk login
  - 'docker info ||:'
  - 'podman info ||:'


upstream:armv7:build:
  stage: build
  tags:
    - arm
  only:
    - web
  image: arm32v7/debian
  before_script:
    - sed -i s:httpredir:ftp.nl:g /etc/apt/sources.list
    - apt-get clean
    - apt-get update
    - apt-get install -y -qq debootstrap
  script:
    - make -C debian-armv7 rootfs.tar
  artifacts:
    paths:
      - debian-armv7/rootfs.tar
    expire_in: 1 day

upstream:armv7:publish:
  stage: publish
  tags:
    - arm
  only:
    - web
  image: registry.gitlab.com/modioab/base-image/fedora-31/container:master
  dependencies:
    - upstream:armv7:build
  script:
    - make -C debian-armv7 build-publish


debian:armv7:build:
  tags:
    - arm
  stage:
    - build
  except:
    - web

  #  image: arm32v7/debian
  #  image: registry.gitlab.com/modioab/base-image/bootstrap:debian-armv7
  image: registry.gitlab.com/modioab/arm-image:oneshot
  before_script:
    - sed -i s:httpredir:ftp.nl:g /etc/apt/sources.list
    - apt-get clean
    - apt-get update
    - apt-get install -y -qq debootstrap
  script:
    - make -C debian-armv7 rootfs.tar
  artifacts:
    paths:
      - debian-armv7/rootfs.tar
    expire_in: 1 day


debian:armv7:publish:
  stage: publish
  image: registry.gitlab.com/modioab/base-image/fedora-31/container:master
  except:
    - web
  tags:
    - x86_64
  dependencies:
    - debian:armv7:build
  script:
    - make -C debian-armv7 build-publish
