# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml

.matrix:
  parallel:
    matrix:
      - SUBDIR:
          - debian9
          - debian10
          - debian11

# Note, this project needs qemu-user-static on the host that builds it.
container:
  # We replace everything except the "rules" section from container publish
  extends:
    - .container:publish
    - .matrix
  tags:
    - arm
  script:
    - podman info
    - make -C ${SUBDIR} login
    - make -C ${SUBDIR} build-publish
...
