# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml

.matrix:
  parallel:
    matrix:
      - SUBDIR:
          - debian9
          - debian10
          - debian11
        PODMAN_PULL:
          - --platform=linux/arm
          # Due to us not being able to pass "platform: " in .gitlab-ci.yml, we
          # should not use multi-arch images for that purpouse.
          # As modio-networks uses these images to check that it built &
          # executes the correct code ( arm code vs. x86, etc), we should not
          # provide both an "arm" and x86_64 image of these.
      - SUBDIR:
          # These images are used to test, and used in reference from
          # Dockerfiles, so we build them for amd64...
          - debian10-test
          - debian11-test
        PODMAN_PULL:
          - --platform=linux/amd64

# Note, this project needs qemu-user-static on the host that builds it.
container:
  # We replace everything except the "rules" section from container publish
  extends:
    - .container:publish
    - .matrix
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_TAG_SUFFIX: "latest"
    - !reference [.container:publish, rules]
  tags:
    - arm
  script:
    - podman info
    - make -C ${SUBDIR} login
    - make -C ${SUBDIR} build-publish
...
